//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arbeitsplan
    {
        public int ID_Arbeitsplan { get; set; }
        public string Baustelle { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public Nullable<int> ID_Material { get; set; }
        public Nullable<int> ID_Mitarbeiter { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Mitarbeiter Mitarbeiter { get; set; }
    }
}
