//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Arbeitsplan = new HashSet<Arbeitsplan>();
        }
    
        public int ID_Material { get; set; }
        public string Name { get; set; }
        public Nullable<int> Anzahl { get; set; }
        public Nullable<decimal> Listenpreis { get; set; }
        public string Hersteller { get; set; }
        public Nullable<int> Gewicht_in_KG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arbeitsplan> Arbeitsplan { get; set; }
    }
}
