//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mitarbeiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mitarbeiter()
        {
            this.Arbeitsplan = new HashSet<Arbeitsplan>();
        }
    
        public int ID_Mitarbeiter { get; set; }
        public string Name { get; set; }
        public string Vorname { get; set; }
        public string Straße { get; set; }
        public Nullable<int> Hausnummer { get; set; }
        public Nullable<int> Postleitzahl { get; set; }
        public Nullable<decimal> Telefonnummer { get; set; }
        public Nullable<System.DateTime> Geburtstag { get; set; }
        public string Ort { get; set; }
        public string Rolle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arbeitsplan> Arbeitsplan { get; set; }
    }
}
